//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenotazioni
    {
        public int id { get; set; }
        public System.DateTime periodoDal { get; set; }
        public System.DateTime periodoAl { get; set; }
        public decimal prezzoTotale { get; set; }
    
        public virtual Camere Camere { get; set; }
        public virtual Clienti Clienti { get; set; }
    }
}
