//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbergoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplementi
    {
        public byte codice { get; set; }
        public string voce { get; set; }
        public decimal prezzo { get; set; }
    }
}
